#!/usr/bin/env bash
#
# SPDX-FileCopyrightText: 2026 Anastasiia-alps-lab
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Builds the GNOME Shell 43/44 variant of the extension (legacy imports, no ESM)
# from the shared core in taksa@alps/extension.js.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC="$HERE/taksa@alps"
DST="$HERE/taksa-legacy@alps"

rm -rf "$DST"
mkdir -p "$DST"

cp "$SRC/stylesheet.css" "$DST/stylesheet.css"
[ -f "$SRC/taksa.png" ] && cp "$SRC/taksa.png" "$DST/taksa.png"

cat > "$DST/metadata.json" <<'EOF'
{
  "uuid": "taksa-legacy@alps",
  "name": "Taksa (GNOME 43/44)",
  "description": "A dachshund burrows across your screen as the Claude Code usage limit runs out. The share of the dog sticking out of the top-right corner is the share of the limit already spent; the rest of it is still visible at the bottom left. The panel indicator shows the same number in percent.",
  "url": "https://github.com/Anastasiia-alps-lab/Taksa",
  "shell-version": ["43", "44"],
  "version-name": "1.0.0"
}
EOF

{
    cat <<'EOF'
/* Taksa — build for GNOME Shell 43/44.
 *
 * SPDX-FileCopyrightText: 2026 Anastasiia-alps-lab
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * GENERATED BY build-legacy.sh — do not edit by hand,
 * make changes in taksa@alps/extension.js. */

const { Clutter, GdkPixbuf, Gio, GLib, Shell, St } = imports.gi;
const Main = imports.ui.main;
const PanelMenu = imports.ui.panelMenu;
const ExtensionUtils = imports.misc.extensionUtils;

EOF
    awk '/^\/\/ ==== CORE START ====$/{f=1;next} /^\/\/ ==== CORE END ====$/{f=0} f' \
        "$SRC/extension.js"
    cat <<'EOF'

let _taksa = null;

function init() {
}

function enable() {
    _taksa = new Taksa(ExtensionUtils.getCurrentExtension().path);
    _taksa.enable();
}

function disable() {
    if (_taksa)
        _taksa.disable();
    _taksa = null;
}
EOF
} > "$DST/extension.js"

if ! grep -q 'class Taksa' "$DST/extension.js"; then
    echo "build-legacy.sh: the core was not extracted, check the CORE START/END markers" >&2
    exit 1
fi

echo "Done: $DST"
